services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: ptdev
      POSTGRES_DB: dbptdev
    ports:

      - "5432:5432"  
    volumes:
      - banco-de-dados-ptdev:/var/lib/postgresql/data  

volumes:
  banco-de-dados-ptdev:  

